"""Nullable processing

Revision ID: fc8988ceb6f1
Revises: 241953179bc7
Create Date: 2026-04-11 09:03:07.129816

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc8988ceb6f1"
down_revision: str | Sequence[str] | None = "241953179bc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("weight_classifications", "processing_cost", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("weight_classifications", "processing_cost", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    # ### end Alembic commands ###
