"""OTP table

Revision ID: 241953179bc7
Revises: ee2c7335979d
Create Date: 2026-04-08 19:25:39.879704

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "241953179bc7"
down_revision: str | Sequence[str] | None = "ee2c7335979d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "one_time_passwords",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("VALIDATE_USER", "VALIDATE_EMAIL", name="otptype"), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(), nullable=False),
        sa.Column("expire_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("user_id", "type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("one_time_passwords")
    # ### end Alembic commands ###
