"""Wheel aggregation table

Revision ID: d48b96d0aa63
Revises: 430e02a42558
Create Date: 2026-03-14 06:58:36.640695

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d48b96d0aa63"
down_revision: str | Sequence[str] | None = "430e02a42558"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wheel_aggregations",
        sa.Column("weight_class_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("median", sa.Float(), nullable=False),
        sa.Column("std", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["weight_class_id"], ["weight_classifications.id"]),
        sa.PrimaryKeyConstraint("weight_class_id", "id"),
    )
    op.add_column("weight_classifications", sa.Column("vehicle_identifier", sa.String(), nullable=False))
    op.add_column("weight_classifications", sa.Column("assigned", sa.Enum(name="weightclassresult"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("weight_classifications", "assigned")
    op.drop_column("weight_classifications", "vehicle_identifier")
    op.drop_table("wheel_aggregations")
    # ### end Alembic commands ###
