"""Wheel feature table

Revision ID: 72eba020e668
Revises: 0a9e72628f29
Create Date: 2026-03-09 13:25:51.265646

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72eba020e668"
down_revision: str | Sequence[str] | None = "0a9e72628f29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wheel_features",
        sa.Column("weight_class_id", sa.Uuid(), nullable=False),
        sa.Column("frame_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rim", sa.JSON(), nullable=False),
        sa.Column("tire", sa.JSON(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["frame_id", "weight_class_id"], ["frames.id", "frames.weight_class_id"]),
        sa.PrimaryKeyConstraint("weight_class_id", "frame_id", "id"),
    )
    op.alter_column(
        "frames",
        "url",
        new_column_name="s3_key",
        existing_type=sa.String(),
        existing_nullable=False,
    )

    op.alter_column(
        "frames",
        "tire_bbxs",
        new_column_name="wheel_bbxs",
        existing_type=sa.JSON(),
        existing_nullable=False,
    )

    # weight_classifications table
    op.alter_column(
        "weight_classifications",
        "video_url",
        new_column_name="video_key",
        existing_type=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # frames table
    op.alter_column(
        "frames",
        "s3_key",
        new_column_name="url",
        existing_type=sa.String(),
        existing_nullable=False,
    )

    op.alter_column(
        "frames",
        "wheel_bbxs",
        new_column_name="tire_bbxs",
        existing_type=sa.JSON(),
        existing_nullable=False,
    )

    # weight_classifications table
    op.alter_column(
        "weight_classifications",
        "video_key",
        new_column_name="video_url",
        existing_type=sa.String(),
        existing_nullable=False,
    )
    op.drop_table("wheel_features")
    # ### end Alembic commands ###
