"""Timezone aware timestamp

Revision ID: 46e0ead0944a
Revises: fc8988ceb6f1
Create Date: 2026-04-11 16:01:57.289630

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "46e0ead0944a"
down_revision: str | Sequence[str] | None = "fc8988ceb6f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column("invoices", sa.Column("invoice_url", sa.String(), nullable=False))
    op.alter_column(
        "invoices",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("invoices", "finished_at", existing_type=postgresql.TIMESTAMP(), type_=sa.TIMESTAMP(timezone=True), existing_nullable=True)
    op.create_unique_constraint("invoices_invoice_url_key", "invoices", ["invoice_url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("invoices_invoice_url_key", "invoices", type_="unique")
    op.alter_column("invoices", "finished_at", existing_type=sa.TIMESTAMP(timezone=True), type_=postgresql.TIMESTAMP(), existing_nullable=True)
    op.alter_column(
        "invoices",
        "created_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("invoices", "invoice_url")
    op.alter_column(
        "api_tokens",
        "created_at",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
