"""Complete DB setup

Revision ID: 96abefda4a66
Revises: d48b96d0aa63
Create Date: 2026-03-29 14:42:31.061343

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96abefda4a66"
down_revision: str | Sequence[str] | None = "d48b96d0aa63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("promoted_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["users.id"]),
        sa.ForeignKeyConstraint(["promoted_by_id"], ["admins.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("funds", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("expire_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_table(
        "api_tokens",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.Enum("UAH", name="currency"), nullable=False),
        sa.Column("status", sa.Enum("PROCESSING", "COMPLETED", "FAILED", name="invoicestatus"), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("reason_code", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("weight_classifications", sa.Column("customer_id", sa.Uuid(), nullable=False))
    op.alter_column("weight_classifications", "processing_cost", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    op.create_foreign_key("customer_fk", "weight_classifications", "customers", ["customer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("customer_fk", "weight_classifications", type_="foreignkey")
    op.alter_column("weight_classifications", "processing_cost", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    op.drop_column("weight_classifications", "customer_id")
    op.drop_table("invoices")
    op.drop_table("api_tokens")
    op.drop_table("sessions")
    op.drop_table("customers")
    op.drop_table("admins")
    # ### end Alembic commands ###
