"""Weight classifications table

Revision ID: 2c8206f745a9
Revises: dccae11471d7
Create Date: 2026-03-07 17:33:10.392562

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c8206f745a9"
down_revision: str | Sequence[str] | None = "dccae11471d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weight_classifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "FRAMES_SPLIT", "MASKS_EXTRACTED", "FEATURES_EXTRACTED", "COMPLETED", name="weightclassstatus"), nullable=False),
        sa.Column("result", sa.Enum("EMPTY", "LOADED", name="weightclassresult"), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("video_url", sa.String(), nullable=False),
        sa.Column("processing_cost", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weight_classifications")
    # ### end Alembic commands ###
