"""Frames table

Revision ID: 0a9e72628f29
Revises: 2c8206f745a9
Create Date: 2026-03-08 14:21:01.354620

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a9e72628f29"
down_revision: str | Sequence[str] | None = "2c8206f745a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "frames",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("weight_class_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Enum("NEW", "PROCESSED", "FAILED", name="framestatus"), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("tire_bbxs", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["weight_class_id"], ["weight_classifications.id"]),
        sa.PrimaryKeyConstraint("id", "weight_class_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("frames")
    # ### end Alembic commands ###
