"""Reset password OTP type

Revision ID: 3f2a0dd402d0
Revises: 46e0ead0944a
Create Date: 2026-04-22 16:29:09.666469

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f2a0dd402d0"
down_revision: str | Sequence[str] | None = "46e0ead0944a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE otptype ADD VALUE 'RESET_PASSWORD'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
