"""Wheel feature rework

Revision ID: 1ae726a1eb8b
Revises: 72eba020e668
Create Date: 2026-03-11 20:44:43.189789

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ae726a1eb8b"
down_revision: str | Sequence[str] | None = "72eba020e668"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wheel_readings",
        sa.Column("weight_class_id", sa.Uuid(), nullable=False),
        sa.Column("frame_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_features", sa.JSON(), nullable=False),
        sa.Column("masked_features", sa.JSON(), nullable=True),
        sa.Column("compression", sa.Float(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["frame_id", "weight_class_id"], ["frames.id", "frames.weight_class_id"]),
        sa.PrimaryKeyConstraint("weight_class_id", "frame_id", "id"),
    )
    op.drop_table("wheel_features")
    op.drop_column("frames", "wheel_bbxs")
    op.drop_column("frames", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("frames", sa.Column("status", postgresql.ENUM("NEW", "PROCESSED", "FAILED", name="framestatus"), autoincrement=False, nullable=False))
    op.add_column("frames", sa.Column("wheel_bbxs", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_table(
        "wheel_features",
        sa.Column("weight_class_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("frame_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("rim", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("tire", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["frame_id", "weight_class_id"],
            ["frames.id", "frames.weight_class_id"],
            name=op.f("wheel_features_frame_id_weight_class_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("weight_class_id", "frame_id", "id", name=op.f("wheel_features_pkey")),
    )
    op.drop_table("wheel_readings")
    # ### end Alembic commands ###
