// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://openapi.json` | (string & {});
};

/**
 * AdminDetailsResponse
 */
export type AdminDetailsResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Promoted By Id
     */
    promoted_by_id: string | null;
};

/**
 * ApiToken
 */
export type ApiToken = {
    /**
     * Token
     */
    token: string;
    /**
     * Customer Id
     */
    customer_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ApiTokenListResponse
 */
export type ApiTokenListResponse = {
    /**
     * Items
     */
    items: Array<ApiToken>;
    /**
     * Total Count
     */
    total_count: number;
};

/**
 * Body_Upload File To Temporary Folder
 */
export type BodyUploadFileToTemporaryFolder = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_Upload File To Temporary Folder Public
 */
export type BodyUploadFileToTemporaryFolderPublic = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_login_api_internal_auth_login_post
 */
export type BodyLoginApiInternalAuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Currency
 */
export type Currency = 'UAH';

/**
 * CustomerDetailsResponse
 */
export type CustomerDetailsResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Funds
     */
    funds: number;
};

/**
 * DemoteAdminResponse
 */
export type DemoteAdminResponse = {
    [key: string]: unknown;
};

/**
 * EmailResetRequest
 */
export type EmailResetRequest = {
    /**
     * New Email
     */
    new_email: string;
};

/**
 * EmailValidateRequest
 */
export type EmailValidateRequest = {
    /**
     * Code
     */
    code: string;
};

/**
 * EmailValidateResponce
 */
export type EmailValidateResponce = {
    [key: string]: unknown;
};

/**
 * FileRespose
 */
export type FileRespose = {
    /**
     * File Id
     */
    file_id: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthCheck
 */
export type HealthCheck = {
    /**
     * Status
     */
    status: number;
    /**
     * Text
     */
    text: string;
};

/**
 * Invoice
 */
export type Invoice = {
    /**
     * Id
     */
    id: string;
    /**
     * Invoice Url
     */
    invoice_url: string;
    /**
     * Customer Id
     */
    customer_id: string;
    /**
     * Amount
     */
    amount: number;
    currency: Currency;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
    status: InvoiceStatus;
    /**
     * Reason
     */
    reason: string | null;
    /**
     * Reason Code
     */
    reason_code: string | null;
};

/**
 * InvoiceListResponse
 */
export type InvoiceListResponse = {
    /**
     * Items
     */
    items: Array<Invoice>;
    /**
     * Total Count
     */
    total_count: number;
};

/**
 * InvoiceStatus
 */
export type InvoiceStatus = 'PROCESSING' | 'COMPLETED' | 'FAILED';

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Token Type
     */
    token_type?: 'bearer';
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Session
     */
    session: string;
};

/**
 * LogoutRequest
 */
export type LogoutRequest = {
    /**
     * Session
     */
    session: string;
};

/**
 * LogoutResponse
 */
export type LogoutResponse = {
    [key: string]: unknown;
};

/**
 * NewAdminRequest
 */
export type NewAdminRequest = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * NewApiTokenRequest
 */
export type NewApiTokenRequest = {
    /**
     * Customer Id
     */
    customer_id: string;
};

/**
 * NewInvoiceRequest
 */
export type NewInvoiceRequest = {
    /**
     * Customer Id
     */
    customer_id: string;
    /**
     * Amount
     */
    amount: number;
};

/**
 * NewUserRequest
 */
export type NewUserRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * NewWeightClassification
 */
export type NewWeightClassification = {
    /**
     * Customer Id
     */
    customer_id: string;
    /**
     * File Id
     */
    file_id: string;
    /**
     * Vehicle Identifier
     */
    vehicle_identifier: string;
    assigned: WeightClassResult;
};

/**
 * OTPResponse
 */
export type OtpResponse = {
    type: OtpType;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Expire At
     */
    expire_at: string;
};

/**
 * OTPType
 */
export type OtpType = 'VALIDATE_USER' | 'VALIDATE_EMAIL' | 'RESET_PASSWORD';

/**
 * PasswordResetRequest
 */
export type PasswordResetRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * PasswordSetRequest
 */
export type PasswordSetRequest = {
    /**
     * Code
     */
    code: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PasswordSetResponce
 */
export type PasswordSetResponce = {
    [key: string]: unknown;
};

/**
 * PublicNewWeightClassification
 */
export type PublicNewWeightClassification = {
    /**
     * File Id
     */
    file_id: string;
    /**
     * Vehicle Identifier
     */
    vehicle_identifier: string;
    assigned: WeightClassResult;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Session
     */
    session: string;
};

/**
 * RefreshResponse
 */
export type RefreshResponse = {
    /**
     * Token Type
     */
    token_type?: 'bearer';
    /**
     * Access Token
     */
    access_token: string;
};

/**
 * TokenData
 */
export type TokenData = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role: Array<UserRole>;
};

/**
 * UserDetailsResponse
 */
export type UserDetailsResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Email Verified
     */
    email_verified: boolean;
    /**
     * Role
     */
    role: Array<UserRole>;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserListResponse
 */
export type UserListResponse = {
    /**
     * Items
     */
    items: Array<UserDetailsResponse>;
    /**
     * Total Count
     */
    total_count: number;
};

/**
 * UserRole
 */
export type UserRole = 'CUSTOMER' | 'ADMIN';

/**
 * ValidateUserRequest
 */
export type ValidateUserRequest = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Code
     */
    code: string;
};

/**
 * ValidateUserResponse
 */
export type ValidateUserResponse = {
    [key: string]: unknown;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WeightClassResult
 */
export type WeightClassResult = 'EMPTY' | 'LOADED';

/**
 * WeightClassStatus
 */
export type WeightClassStatus = 'PENDING' | 'FRAMES_SPLIT' | 'MASKS_EXTRACTED' | 'FEATURES_EXTRACTED' | 'COMPLETED';

/**
 * WeightClassificationItem
 */
export type WeightClassificationItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Vehicle Identifier
     */
    vehicle_identifier: string;
    /**
     * Customer Id
     */
    customer_id: string;
    status: WeightClassStatus;
    result: WeightClassResult | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Processing Cost
     */
    processing_cost: number | null;
};

/**
 * WeightClassificationListResponse
 */
export type WeightClassificationListResponse = {
    /**
     * Items
     */
    items: Array<WeightClassificationItem>;
    /**
     * Total Count
     */
    total_count: number;
};

/**
 * WeightClassificationResponse
 */
export type WeightClassificationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Vehicle Identifier
     */
    vehicle_identifier: string;
    /**
     * Customer Id
     */
    customer_id: string;
    status: WeightClassStatus;
    assigned: WeightClassResult;
    result: WeightClassResult | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Video Url
     */
    video_url: string;
    /**
     * Processing Cost
     */
    processing_cost: number | null;
};

export type HealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthCheck;
};

export type HealthApiHealthGetResponse = HealthApiHealthGetResponses[keyof HealthApiHealthGetResponses];

export type GetUsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Roles
         */
        roles?: Array<UserRole> | null;
        /**
         * Email Like
         */
        email_like?: string | null;
    };
    url: '/api/internal/users/';
};

export type GetUsersListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersListError = GetUsersListErrors[keyof GetUsersListErrors];

export type GetUsersListResponses = {
    /**
     * Successful Response
     */
    200: UserListResponse;
};

export type GetUsersListResponse = GetUsersListResponses[keyof GetUsersListResponses];

export type RequestEmailResetData = {
    body: EmailResetRequest;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/internal/users/{user_id}/reset_email/';
};

export type RequestEmailResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestEmailResetError = RequestEmailResetErrors[keyof RequestEmailResetErrors];

export type RequestEmailResetResponses = {
    /**
     * Successful Response
     */
    200: OtpResponse;
};

export type RequestEmailResetResponse = RequestEmailResetResponses[keyof RequestEmailResetResponses];

export type ValidateEmailResetData = {
    body: EmailValidateRequest;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/internal/users/{user_id}/reset_email/validate';
};

export type ValidateEmailResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateEmailResetError = ValidateEmailResetErrors[keyof ValidateEmailResetErrors];

export type ValidateEmailResetResponses = {
    /**
     * Successful Response
     */
    200: EmailValidateResponce;
};

export type ValidateEmailResetResponse = ValidateEmailResetResponses[keyof ValidateEmailResetResponses];

export type GetUserDetailsData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/internal/users/{user_id}/';
};

export type GetUserDetailsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserDetailsError = GetUserDetailsErrors[keyof GetUserDetailsErrors];

export type GetUserDetailsResponses = {
    /**
     * Successful Response
     */
    200: UserDetailsResponse;
};

export type GetUserDetailsResponse = GetUserDetailsResponses[keyof GetUserDetailsResponses];

export type NewUserData = {
    body: NewUserRequest;
    path?: never;
    query?: never;
    url: '/api/internal/users/signup/';
};

export type NewUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewUserError = NewUserErrors[keyof NewUserErrors];

export type NewUserResponses = {
    /**
     * Successful Response
     */
    200: OtpResponse;
};

export type NewUserResponse = NewUserResponses[keyof NewUserResponses];

export type ValidateNewUserData = {
    body: ValidateUserRequest;
    path?: never;
    query?: never;
    url: '/api/internal/users/signup/validate';
};

export type ValidateNewUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateNewUserError = ValidateNewUserErrors[keyof ValidateNewUserErrors];

export type ValidateNewUserResponses = {
    /**
     * Successful Response
     */
    200: ValidateUserResponse;
};

export type ValidateNewUserResponse = ValidateNewUserResponses[keyof ValidateNewUserResponses];

export type RequestPasswordResetData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/internal/users/reset_password/';
};

export type RequestPasswordResetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestPasswordResetError = RequestPasswordResetErrors[keyof RequestPasswordResetErrors];

export type RequestPasswordResetResponses = {
    /**
     * Successful Response
     */
    200: OtpResponse;
};

export type RequestPasswordResetResponse = RequestPasswordResetResponses[keyof RequestPasswordResetResponses];

export type SetNewPasswordData = {
    body: PasswordSetRequest;
    path?: never;
    query?: never;
    url: '/api/internal/users/reset_password/set';
};

export type SetNewPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetNewPasswordError = SetNewPasswordErrors[keyof SetNewPasswordErrors];

export type SetNewPasswordResponses = {
    /**
     * Successful Response
     */
    200: PasswordSetResponce;
};

export type SetNewPasswordResponse = SetNewPasswordResponses[keyof SetNewPasswordResponses];

export type LoginApiInternalAuthLoginPostData = {
    body: BodyLoginApiInternalAuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/internal/auth/login';
};

export type LoginApiInternalAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiInternalAuthLoginPostError = LoginApiInternalAuthLoginPostErrors[keyof LoginApiInternalAuthLoginPostErrors];

export type LoginApiInternalAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginApiInternalAuthLoginPostResponse = LoginApiInternalAuthLoginPostResponses[keyof LoginApiInternalAuthLoginPostResponses];

export type LogoutApiInternalAuthLogoutPostData = {
    body: LogoutRequest;
    path?: never;
    query?: never;
    url: '/api/internal/auth/logout';
};

export type LogoutApiInternalAuthLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiInternalAuthLogoutPostError = LogoutApiInternalAuthLogoutPostErrors[keyof LogoutApiInternalAuthLogoutPostErrors];

export type LogoutApiInternalAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: LogoutResponse;
};

export type LogoutApiInternalAuthLogoutPostResponse = LogoutApiInternalAuthLogoutPostResponses[keyof LogoutApiInternalAuthLogoutPostResponses];

export type MeApiInternalAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/auth/me';
};

export type MeApiInternalAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: TokenData;
};

export type MeApiInternalAuthMeGetResponse = MeApiInternalAuthMeGetResponses[keyof MeApiInternalAuthMeGetResponses];

export type RefreshApiInternalAuthRefreshPostData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/internal/auth/refresh';
};

export type RefreshApiInternalAuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshApiInternalAuthRefreshPostError = RefreshApiInternalAuthRefreshPostErrors[keyof RefreshApiInternalAuthRefreshPostErrors];

export type RefreshApiInternalAuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: RefreshResponse;
};

export type RefreshApiInternalAuthRefreshPostResponse = RefreshApiInternalAuthRefreshPostResponses[keyof RefreshApiInternalAuthRefreshPostResponses];

export type GetCustomerDetailsData = {
    body?: never;
    path: {
        /**
         * Customer Id
         */
        customer_id: string;
    };
    query?: never;
    url: '/api/internal/customers/{customer_id}/';
};

export type GetCustomerDetailsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCustomerDetailsError = GetCustomerDetailsErrors[keyof GetCustomerDetailsErrors];

export type GetCustomerDetailsResponses = {
    /**
     * Successful Response
     */
    200: CustomerDetailsResponse;
};

export type GetCustomerDetailsResponse = GetCustomerDetailsResponses[keyof GetCustomerDetailsResponses];

export type GetWeightClassificationListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Customer Ids
         */
        customer_ids?: Array<string> | null;
    };
    url: '/api/internal/weight_classifications/';
};

export type GetWeightClassificationListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWeightClassificationListError = GetWeightClassificationListErrors[keyof GetWeightClassificationListErrors];

export type GetWeightClassificationListResponses = {
    /**
     * Successful Response
     */
    200: WeightClassificationListResponse;
};

export type GetWeightClassificationListResponse = GetWeightClassificationListResponses[keyof GetWeightClassificationListResponses];

export type NewWeightClassificationData = {
    body: NewWeightClassification;
    path?: never;
    query?: never;
    url: '/api/internal/weight_classifications/';
};

export type NewWeightClassificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewWeightClassificationError = NewWeightClassificationErrors[keyof NewWeightClassificationErrors];

export type NewWeightClassificationResponses = {
    /**
     * Successful Response
     */
    200: WeightClassificationResponse;
};

export type NewWeightClassificationResponse = NewWeightClassificationResponses[keyof NewWeightClassificationResponses];

export type GetWeightClassificationDetailsData = {
    body?: never;
    path: {
        /**
         * Weight Class Id
         */
        weight_class_id: string;
    };
    query?: never;
    url: '/api/internal/weight_classifications/{weight_class_id}/';
};

export type GetWeightClassificationDetailsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWeightClassificationDetailsError = GetWeightClassificationDetailsErrors[keyof GetWeightClassificationDetailsErrors];

export type GetWeightClassificationDetailsResponses = {
    /**
     * Successful Response
     */
    200: WeightClassificationResponse;
};

export type GetWeightClassificationDetailsResponse = GetWeightClassificationDetailsResponses[keyof GetWeightClassificationDetailsResponses];

export type GetInvoicesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Customer Ids
         */
        customer_ids?: Array<string> | null;
    };
    url: '/api/internal/invoices/';
};

export type GetInvoicesListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInvoicesListError = GetInvoicesListErrors[keyof GetInvoicesListErrors];

export type GetInvoicesListResponses = {
    /**
     * Successful Response
     */
    200: InvoiceListResponse;
};

export type GetInvoicesListResponse = GetInvoicesListResponses[keyof GetInvoicesListResponses];

export type CreateNewInvoiceData = {
    body: NewInvoiceRequest;
    path?: never;
    query?: never;
    url: '/api/internal/invoices/';
};

export type CreateNewInvoiceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNewInvoiceError = CreateNewInvoiceErrors[keyof CreateNewInvoiceErrors];

export type CreateNewInvoiceResponses = {
    /**
     * Successful Response
     */
    200: Invoice;
};

export type CreateNewInvoiceResponse = CreateNewInvoiceResponses[keyof CreateNewInvoiceResponses];

export type GetInvoiceDetailsData = {
    body?: never;
    path: {
        /**
         * Invoice Id
         */
        invoice_id: string;
    };
    query?: never;
    url: '/api/internal/invoices/{invoice_id}/';
};

export type GetInvoiceDetailsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInvoiceDetailsError = GetInvoiceDetailsErrors[keyof GetInvoiceDetailsErrors];

export type GetInvoiceDetailsResponses = {
    /**
     * Successful Response
     */
    200: Invoice;
};

export type GetInvoiceDetailsResponse = GetInvoiceDetailsResponses[keyof GetInvoiceDetailsResponses];

export type GetApiTokenListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Customer Ids
         */
        customer_ids?: Array<string> | null;
    };
    url: '/api/internal/api_tokens/';
};

export type GetApiTokenListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiTokenListError = GetApiTokenListErrors[keyof GetApiTokenListErrors];

export type GetApiTokenListResponses = {
    /**
     * Successful Response
     */
    200: ApiTokenListResponse;
};

export type GetApiTokenListResponse = GetApiTokenListResponses[keyof GetApiTokenListResponses];

export type CreateNewApiTokenData = {
    body: NewApiTokenRequest;
    path?: never;
    query?: never;
    url: '/api/internal/api_tokens/';
};

export type CreateNewApiTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNewApiTokenError = CreateNewApiTokenErrors[keyof CreateNewApiTokenErrors];

export type CreateNewApiTokenResponses = {
    /**
     * Successful Response
     */
    200: ApiToken;
};

export type CreateNewApiTokenResponse = CreateNewApiTokenResponses[keyof CreateNewApiTokenResponses];

export type DeleteApiTokenData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Token
         */
        token: string;
    };
    url: '/api/internal/api_tokens/{api_token}/';
};

export type DeleteApiTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiTokenError = DeleteApiTokenErrors[keyof DeleteApiTokenErrors];

export type DeleteApiTokenResponses = {
    /**
     * Successful Response
     */
    200: ApiToken;
};

export type DeleteApiTokenResponse = DeleteApiTokenResponses[keyof DeleteApiTokenResponses];

export type UploadFileToTemporaryFolderData = {
    body: BodyUploadFileToTemporaryFolder;
    path?: never;
    query?: never;
    url: '/api/internal/upload';
};

export type UploadFileToTemporaryFolderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileToTemporaryFolderError = UploadFileToTemporaryFolderErrors[keyof UploadFileToTemporaryFolderErrors];

export type UploadFileToTemporaryFolderResponses = {
    /**
     * Successful Response
     */
    200: FileRespose;
};

export type UploadFileToTemporaryFolderResponse = UploadFileToTemporaryFolderResponses[keyof UploadFileToTemporaryFolderResponses];

export type CreateNewAdminData = {
    body: NewAdminRequest;
    path?: never;
    query?: never;
    url: '/api/internal/admins/';
};

export type CreateNewAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNewAdminError = CreateNewAdminErrors[keyof CreateNewAdminErrors];

export type CreateNewAdminResponses = {
    /**
     * Successful Response
     */
    200: AdminDetailsResponse;
};

export type CreateNewAdminResponse = CreateNewAdminResponses[keyof CreateNewAdminResponses];

export type DemoteAdminData = {
    body?: never;
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/api/internal/admins/{admin_id}/';
};

export type DemoteAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DemoteAdminError = DemoteAdminErrors[keyof DemoteAdminErrors];

export type DemoteAdminResponses = {
    /**
     * Successful Response
     */
    200: DemoteAdminResponse;
};

export type DemoteAdminResponse2 = DemoteAdminResponses[keyof DemoteAdminResponses];

export type GetAdminDetailsData = {
    body?: never;
    path: {
        /**
         * Admin Id
         */
        admin_id: string;
    };
    query?: never;
    url: '/api/internal/admins/{admin_id}/';
};

export type GetAdminDetailsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAdminDetailsError = GetAdminDetailsErrors[keyof GetAdminDetailsErrors];

export type GetAdminDetailsResponses = {
    /**
     * Successful Response
     */
    200: AdminDetailsResponse;
};

export type GetAdminDetailsResponse = GetAdminDetailsResponses[keyof GetAdminDetailsResponses];

export type GetWeightClassificationListPublicData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Customer Ids
         */
        customer_ids?: Array<string> | null;
    };
    url: '/api/public/weight_classifications/';
};

export type GetWeightClassificationListPublicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWeightClassificationListPublicError = GetWeightClassificationListPublicErrors[keyof GetWeightClassificationListPublicErrors];

export type GetWeightClassificationListPublicResponses = {
    /**
     * Successful Response
     */
    200: WeightClassificationListResponse;
};

export type GetWeightClassificationListPublicResponse = GetWeightClassificationListPublicResponses[keyof GetWeightClassificationListPublicResponses];

export type NewWeightClassificationPublicData = {
    body: PublicNewWeightClassification;
    path?: never;
    query?: never;
    url: '/api/public/weight_classifications/';
};

export type NewWeightClassificationPublicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewWeightClassificationPublicError = NewWeightClassificationPublicErrors[keyof NewWeightClassificationPublicErrors];

export type NewWeightClassificationPublicResponses = {
    /**
     * Successful Response
     */
    200: WeightClassificationResponse;
};

export type NewWeightClassificationPublicResponse = NewWeightClassificationPublicResponses[keyof NewWeightClassificationPublicResponses];

export type GetWeightClassificationDetailsPublicData = {
    body?: never;
    path: {
        /**
         * Weight Class Id
         */
        weight_class_id: string;
    };
    query?: never;
    url: '/api/public/weight_classifications/{weight_class_id}/';
};

export type GetWeightClassificationDetailsPublicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWeightClassificationDetailsPublicError = GetWeightClassificationDetailsPublicErrors[keyof GetWeightClassificationDetailsPublicErrors];

export type GetWeightClassificationDetailsPublicResponses = {
    /**
     * Successful Response
     */
    200: WeightClassificationResponse;
};

export type GetWeightClassificationDetailsPublicResponse = GetWeightClassificationDetailsPublicResponses[keyof GetWeightClassificationDetailsPublicResponses];

export type UploadFileToTemporaryFolderPublicData = {
    body: BodyUploadFileToTemporaryFolderPublic;
    path?: never;
    query?: never;
    url: '/api/public/upload';
};

export type UploadFileToTemporaryFolderPublicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileToTemporaryFolderPublicError = UploadFileToTemporaryFolderPublicErrors[keyof UploadFileToTemporaryFolderPublicErrors];

export type UploadFileToTemporaryFolderPublicResponses = {
    /**
     * Successful Response
     */
    200: FileRespose;
};

export type UploadFileToTemporaryFolderPublicResponse = UploadFileToTemporaryFolderPublicResponses[keyof UploadFileToTemporaryFolderPublicResponses];
