apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
      - name: ecommerce-app
        image: ghcr.io/mykhailorp/ecommerce-app:latest
        command: ["uv", "run", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080"]
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/health/
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

        envFrom:
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: postgres-config

        env:
        - name: POSTGRES_DRIVER
          value: asyncpg
        - name: SERVICE_NAME
          value: api

        - name: POSTGRES_DRIVER
          value: asyncpg
        - name: SERVICE_NAME
          value: api

---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce-app-service
spec:
  type: NodePort
  selector:
    app: ecommerce-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
