// This file is auto-generated by @hey-api/openapi-ts

import {
  type _JSONValue,
  defineQueryOptions,
  type UseMutationOptions,
} from "@pinia/colada";

import { serializeQueryKeyValue } from "../client";
import { client } from "../client.gen";
import {
  createNewAdmin,
  createNewApiToken,
  createNewInvoice,
  deleteApiToken,
  demoteAdmin,
  getAccountDetails,
  getAdminDetails,
  getApiTokenList,
  getCustomerDetails,
  getInvoiceDetails,
  getInvoicesList,
  getMe,
  getUserDetails,
  getUsersList,
  getWeightClassificationDetails,
  getWeightClassificationDetailsPublic,
  getWeightClassificationList,
  getWeightClassificationListPublic,
  healthApiHealthGet,
  login,
  logout,
  newUser,
  newWeightClassification,
  newWeightClassificationPublic,
  type Options,
  refreshToken,
  requestEmailReset,
  requestPasswordReset,
  setNewPassword,
  uploadFileToTemporaryFolder,
  uploadFileToTemporaryFolderPublic,
  validateEmailReset,
  validateNewUser,
} from "../sdk.gen";
import type {
  CreateNewAdminData,
  CreateNewAdminError,
  CreateNewAdminResponse,
  CreateNewApiTokenData,
  CreateNewApiTokenError,
  CreateNewApiTokenResponse,
  CreateNewInvoiceData,
  CreateNewInvoiceError,
  CreateNewInvoiceResponse,
  DeleteApiTokenData,
  DeleteApiTokenError,
  DeleteApiTokenResponse,
  DemoteAdminData,
  DemoteAdminError,
  DemoteAdminResponse2,
  GetAccountDetailsData,
  GetAccountDetailsError,
  GetAccountDetailsResponse,
  GetAdminDetailsData,
  GetAdminDetailsError,
  GetAdminDetailsResponse,
  GetApiTokenListData,
  GetApiTokenListError,
  GetApiTokenListResponse,
  GetCustomerDetailsData,
  GetCustomerDetailsError,
  GetCustomerDetailsResponse,
  GetInvoiceDetailsData,
  GetInvoiceDetailsError,
  GetInvoiceDetailsResponse,
  GetInvoicesListData,
  GetInvoicesListError,
  GetInvoicesListResponse,
  GetMeData,
  GetMeResponse,
  GetUserDetailsData,
  GetUserDetailsError,
  GetUserDetailsResponse,
  GetUsersListData,
  GetUsersListError,
  GetUsersListResponse,
  GetWeightClassificationDetailsData,
  GetWeightClassificationDetailsError,
  GetWeightClassificationDetailsPublicData,
  GetWeightClassificationDetailsPublicError,
  GetWeightClassificationDetailsPublicResponse,
  GetWeightClassificationDetailsResponse,
  GetWeightClassificationListData,
  GetWeightClassificationListError,
  GetWeightClassificationListPublicData,
  GetWeightClassificationListPublicError,
  GetWeightClassificationListPublicResponse,
  GetWeightClassificationListResponse,
  HealthApiHealthGetData,
  HealthApiHealthGetResponse,
  LoginData,
  LoginError,
  LoginResponse2,
  LogoutData,
  LogoutError,
  LogoutResponse2,
  NewUserData,
  NewUserError,
  NewUserResponse,
  NewWeightClassificationData,
  NewWeightClassificationError,
  NewWeightClassificationPublicData,
  NewWeightClassificationPublicError,
  NewWeightClassificationPublicResponse,
  NewWeightClassificationResponse,
  RefreshTokenData,
  RefreshTokenError,
  RefreshTokenResponse,
  RequestEmailResetData,
  RequestEmailResetError,
  RequestEmailResetResponse,
  RequestPasswordResetData,
  RequestPasswordResetError,
  RequestPasswordResetResponse,
  SetNewPasswordData,
  SetNewPasswordError,
  SetNewPasswordResponse,
  UploadFileToTemporaryFolderData,
  UploadFileToTemporaryFolderError,
  UploadFileToTemporaryFolderPublicData,
  UploadFileToTemporaryFolderPublicError,
  UploadFileToTemporaryFolderPublicResponse,
  UploadFileToTemporaryFolderResponse,
  ValidateEmailResetData,
  ValidateEmailResetError,
  ValidateEmailResetResponse,
  ValidateNewUserData,
  ValidateNewUserError,
  ValidateNewUserResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "path"> & {
    _id: string;
    baseUrl?: _JSONValue;
    body?: _JSONValue;
    query?: _JSONValue;
    tags?: _JSONValue;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (tags) {
    params.tags = tags as unknown as _JSONValue;
  }
  if (options?.body !== undefined) {
    const normalizedBody = serializeQueryKeyValue(options.body);
    if (normalizedBody !== undefined) {
      params.body = normalizedBody;
    }
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query !== undefined) {
    const normalizedQuery = serializeQueryKeyValue(options.query);
    if (normalizedQuery !== undefined) {
      params.query = normalizedQuery;
    }
  }
  return [params];
};

export const healthApiHealthGetQueryKey = (
  options?: Options<HealthApiHealthGetData>,
) => createQueryKey("healthApiHealthGet", options);

/**
 * Health
 */
export const healthApiHealthGetQuery = defineQueryOptions<
  Options<HealthApiHealthGetData>,
  HealthApiHealthGetResponse,
  Error
>((options?: Options<HealthApiHealthGetData>) => ({
  key: healthApiHealthGetQueryKey(options),
  query: async (context) => {
    const { data } = await healthApiHealthGet({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const getUsersListQueryKey = (options?: Options<GetUsersListData>) =>
  createQueryKey("getUsersList", options);

/**
 * Get Users
 */
export const getUsersListQuery = defineQueryOptions<
  Options<GetUsersListData>,
  GetUsersListResponse,
  GetUsersListError
>((options?: Options<GetUsersListData>) => ({
  key: getUsersListQueryKey(options),
  query: async (context) => {
    const { data } = await getUsersList({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Reset Email
 */
export const requestEmailResetMutation = (
  options?: Partial<Options<RequestEmailResetData>>,
): UseMutationOptions<
  RequestEmailResetResponse,
  Options<RequestEmailResetData>,
  RequestEmailResetError
> => ({
  mutation: async (vars) => {
    const { data } = await requestEmailReset({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Validate Email
 */
export const validateEmailResetMutation = (
  options?: Partial<Options<ValidateEmailResetData>>,
): UseMutationOptions<
  ValidateEmailResetResponse,
  Options<ValidateEmailResetData>,
  ValidateEmailResetError
> => ({
  mutation: async (vars) => {
    const { data } = await validateEmailReset({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export const getUserDetailsQueryKey = (options: Options<GetUserDetailsData>) =>
  createQueryKey("getUserDetails", options);

/**
 * Get User
 */
export const getUserDetailsQuery = defineQueryOptions<
  Options<GetUserDetailsData>,
  GetUserDetailsResponse,
  GetUserDetailsError
>((options: Options<GetUserDetailsData>) => ({
  key: getUserDetailsQueryKey(options),
  query: async (context) => {
    const { data } = await getUserDetails({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Create New User
 */
export const newUserMutation = (
  options?: Partial<Options<NewUserData>>,
): UseMutationOptions<NewUserResponse, Options<NewUserData>, NewUserError> => ({
  mutation: async (vars) => {
    const { data } = await newUser({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Validate New User
 */
export const validateNewUserMutation = (
  options?: Partial<Options<ValidateNewUserData>>,
): UseMutationOptions<
  ValidateNewUserResponse,
  Options<ValidateNewUserData>,
  ValidateNewUserError
> => ({
  mutation: async (vars) => {
    const { data } = await validateNewUser({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Reset Password
 */
export const requestPasswordResetMutation = (
  options?: Partial<Options<RequestPasswordResetData>>,
): UseMutationOptions<
  RequestPasswordResetResponse,
  Options<RequestPasswordResetData>,
  RequestPasswordResetError
> => ({
  mutation: async (vars) => {
    const { data } = await requestPasswordReset({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Set Password
 */
export const setNewPasswordMutation = (
  options?: Partial<Options<SetNewPasswordData>>,
): UseMutationOptions<
  SetNewPasswordResponse,
  Options<SetNewPasswordData>,
  SetNewPasswordError
> => ({
  mutation: async (vars) => {
    const { data } = await setNewPassword({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Login
 */
export const loginMutation = (
  options?: Partial<Options<LoginData>>,
): UseMutationOptions<LoginResponse2, Options<LoginData>, LoginError> => ({
  mutation: async (vars) => {
    const { data } = await login({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Logout
 */
export const logoutMutation = (
  options?: Partial<Options<LogoutData>>,
): UseMutationOptions<LogoutResponse2, Options<LogoutData>, LogoutError> => ({
  mutation: async (vars) => {
    const { data } = await logout({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export const getMeQueryKey = (options?: Options<GetMeData>) =>
  createQueryKey("getMe", options);

/**
 * Me
 */
export const getMeQuery = defineQueryOptions<
  Options<GetMeData>,
  GetMeResponse,
  Error
>((options?: Options<GetMeData>) => ({
  key: getMeQueryKey(options),
  query: async (context) => {
    const { data } = await getMe({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Refresh
 */
export const refreshTokenMutation = (
  options?: Partial<Options<RefreshTokenData>>,
): UseMutationOptions<
  RefreshTokenResponse,
  Options<RefreshTokenData>,
  RefreshTokenError
> => ({
  mutation: async (vars) => {
    const { data } = await refreshToken({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export const getCustomerDetailsQueryKey = (
  options: Options<GetCustomerDetailsData>,
) => createQueryKey("getCustomerDetails", options);

/**
 * Get Customer
 */
export const getCustomerDetailsQuery = defineQueryOptions<
  Options<GetCustomerDetailsData>,
  GetCustomerDetailsResponse,
  GetCustomerDetailsError
>((options: Options<GetCustomerDetailsData>) => ({
  key: getCustomerDetailsQueryKey(options),
  query: async (context) => {
    const { data } = await getCustomerDetails({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const getWeightClassificationListQueryKey = (
  options?: Options<GetWeightClassificationListData>,
) => createQueryKey("getWeightClassificationList", options);

/**
 * Get Weight Classifications
 */
export const getWeightClassificationListQuery = defineQueryOptions<
  Options<GetWeightClassificationListData>,
  GetWeightClassificationListResponse,
  GetWeightClassificationListError
>((options?: Options<GetWeightClassificationListData>) => ({
  key: getWeightClassificationListQueryKey(options),
  query: async (context) => {
    const { data } = await getWeightClassificationList({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Create Weight Classification
 */
export const newWeightClassificationMutation = (
  options?: Partial<Options<NewWeightClassificationData>>,
): UseMutationOptions<
  NewWeightClassificationResponse,
  Options<NewWeightClassificationData>,
  NewWeightClassificationError
> => ({
  mutation: async (vars) => {
    const { data } = await newWeightClassification({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export const getWeightClassificationDetailsQueryKey = (
  options: Options<GetWeightClassificationDetailsData>,
) => createQueryKey("getWeightClassificationDetails", options);

/**
 * Get Weight Classification
 */
export const getWeightClassificationDetailsQuery = defineQueryOptions<
  Options<GetWeightClassificationDetailsData>,
  GetWeightClassificationDetailsResponse,
  GetWeightClassificationDetailsError
>((options: Options<GetWeightClassificationDetailsData>) => ({
  key: getWeightClassificationDetailsQueryKey(options),
  query: async (context) => {
    const { data } = await getWeightClassificationDetails({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const getInvoicesListQueryKey = (
  options?: Options<GetInvoicesListData>,
) => createQueryKey("getInvoicesList", options);

/**
 * Get Invoices
 */
export const getInvoicesListQuery = defineQueryOptions<
  Options<GetInvoicesListData>,
  GetInvoicesListResponse,
  GetInvoicesListError
>((options?: Options<GetInvoicesListData>) => ({
  key: getInvoicesListQueryKey(options),
  query: async (context) => {
    const { data } = await getInvoicesList({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * New Invoice
 */
export const createNewInvoiceMutation = (
  options?: Partial<Options<CreateNewInvoiceData>>,
): UseMutationOptions<
  CreateNewInvoiceResponse,
  Options<CreateNewInvoiceData>,
  CreateNewInvoiceError
> => ({
  mutation: async (vars) => {
    const { data } = await createNewInvoice({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export const getInvoiceDetailsQueryKey = (
  options: Options<GetInvoiceDetailsData>,
) => createQueryKey("getInvoiceDetails", options);

/**
 * Get Invoice
 */
export const getInvoiceDetailsQuery = defineQueryOptions<
  Options<GetInvoiceDetailsData>,
  GetInvoiceDetailsResponse,
  GetInvoiceDetailsError
>((options: Options<GetInvoiceDetailsData>) => ({
  key: getInvoiceDetailsQueryKey(options),
  query: async (context) => {
    const { data } = await getInvoiceDetails({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const getApiTokenListQueryKey = (
  options?: Options<GetApiTokenListData>,
) => createQueryKey("getApiTokenList", options);

/**
 * Get Api Tokens
 */
export const getApiTokenListQuery = defineQueryOptions<
  Options<GetApiTokenListData>,
  GetApiTokenListResponse,
  GetApiTokenListError
>((options?: Options<GetApiTokenListData>) => ({
  key: getApiTokenListQueryKey(options),
  query: async (context) => {
    const { data } = await getApiTokenList({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * New Token
 */
export const createNewApiTokenMutation = (
  options?: Partial<Options<CreateNewApiTokenData>>,
): UseMutationOptions<
  CreateNewApiTokenResponse,
  Options<CreateNewApiTokenData>,
  CreateNewApiTokenError
> => ({
  mutation: async (vars) => {
    const { data } = await createNewApiToken({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Delete Token
 */
export const deleteApiTokenMutation = (
  options?: Partial<Options<DeleteApiTokenData>>,
): UseMutationOptions<
  DeleteApiTokenResponse,
  Options<DeleteApiTokenData>,
  DeleteApiTokenError
> => ({
  mutation: async (vars) => {
    const { data } = await deleteApiToken({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Upload
 */
export const uploadFileToTemporaryFolderMutation = (
  options?: Partial<Options<UploadFileToTemporaryFolderData>>,
): UseMutationOptions<
  UploadFileToTemporaryFolderResponse,
  Options<UploadFileToTemporaryFolderData>,
  UploadFileToTemporaryFolderError
> => ({
  mutation: async (vars) => {
    const { data } = await uploadFileToTemporaryFolder({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * New Admin
 */
export const createNewAdminMutation = (
  options?: Partial<Options<CreateNewAdminData>>,
): UseMutationOptions<
  CreateNewAdminResponse,
  Options<CreateNewAdminData>,
  CreateNewAdminError
> => ({
  mutation: async (vars) => {
    const { data } = await createNewAdmin({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Delete Admin
 */
export const demoteAdminMutation = (
  options?: Partial<Options<DemoteAdminData>>,
): UseMutationOptions<
  DemoteAdminResponse2,
  Options<DemoteAdminData>,
  DemoteAdminError
> => ({
  mutation: async (vars) => {
    const { data } = await demoteAdmin({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export const getAdminDetailsQueryKey = (
  options: Options<GetAdminDetailsData>,
) => createQueryKey("getAdminDetails", options);

/**
 * Get Admin
 */
export const getAdminDetailsQuery = defineQueryOptions<
  Options<GetAdminDetailsData>,
  GetAdminDetailsResponse,
  GetAdminDetailsError
>((options: Options<GetAdminDetailsData>) => ({
  key: getAdminDetailsQueryKey(options),
  query: async (context) => {
    const { data } = await getAdminDetails({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const getAccountDetailsQueryKey = (
  options: Options<GetAccountDetailsData>,
) => createQueryKey("getAccountDetails", options);

/**
 * Get User
 */
export const getAccountDetailsQuery = defineQueryOptions<
  Options<GetAccountDetailsData>,
  GetAccountDetailsResponse,
  GetAccountDetailsError
>((options: Options<GetAccountDetailsData>) => ({
  key: getAccountDetailsQueryKey(options),
  query: async (context) => {
    const { data } = await getAccountDetails({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const getWeightClassificationListPublicQueryKey = (
  options?: Options<GetWeightClassificationListPublicData>,
) => createQueryKey("getWeightClassificationListPublic", options);

/**
 * Get Weight Classifications Public
 */
export const getWeightClassificationListPublicQuery = defineQueryOptions<
  Options<GetWeightClassificationListPublicData>,
  GetWeightClassificationListPublicResponse,
  GetWeightClassificationListPublicError
>((options?: Options<GetWeightClassificationListPublicData>) => ({
  key: getWeightClassificationListPublicQueryKey(options),
  query: async (context) => {
    const { data } = await getWeightClassificationListPublic({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Create Weight Classification
 */
export const newWeightClassificationPublicMutation = (
  options?: Partial<Options<NewWeightClassificationPublicData>>,
): UseMutationOptions<
  NewWeightClassificationPublicResponse,
  Options<NewWeightClassificationPublicData>,
  NewWeightClassificationPublicError
> => ({
  mutation: async (vars) => {
    const { data } = await newWeightClassificationPublic({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export const getWeightClassificationDetailsPublicQueryKey = (
  options: Options<GetWeightClassificationDetailsPublicData>,
) => createQueryKey("getWeightClassificationDetailsPublic", options);

/**
 * Get Weight Classification
 */
export const getWeightClassificationDetailsPublicQuery = defineQueryOptions<
  Options<GetWeightClassificationDetailsPublicData>,
  GetWeightClassificationDetailsPublicResponse,
  GetWeightClassificationDetailsPublicError
>((options: Options<GetWeightClassificationDetailsPublicData>) => ({
  key: getWeightClassificationDetailsPublicQueryKey(options),
  query: async (context) => {
    const { data } = await getWeightClassificationDetailsPublic({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Upload
 */
export const uploadFileToTemporaryFolderPublicMutation = (
  options?: Partial<Options<UploadFileToTemporaryFolderPublicData>>,
): UseMutationOptions<
  UploadFileToTemporaryFolderPublicResponse,
  Options<UploadFileToTemporaryFolderPublicData>,
  UploadFileToTemporaryFolderPublicError
> => ({
  mutation: async (vars) => {
    const { data } = await uploadFileToTemporaryFolderPublic({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});
