name: Apply Helm

on:
  push:
env:
  IMAGE_NAME: ecommerce-app
jobs:
  helm:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Install Tools
        run: sudo apt-get update && sudo snap install helm --classic
      - 
        name: Run Master Validation Script
        run: |
          chmod +x ./tests/lab4_test.sh
          ./tests/lab4_test.sh